import { Business, Category } from './types';

// Admin phone number for receiving registration requests
export const ADMIN_PHONE_NUMBER = '905550000000'; 

export const MOCK_BUSINESSES: Business[] = [
  {
    id: '1',
    name: 'Lezzet Konağı',
    category: Category.FOOD,
    description: 'Yöresel ev yemekleri ve serpme kahvaltı.',
    address: 'Cumhuriyet Cad. No:12',
    phone: '905551234567', 
    imageUrl: 'https://picsum.photos/400/300?random=1',
    rating: 4.8,
    tags: ['kahvaltı', 'mantı', 'ev yemeği', 'bahçe'],
    status: 'approved',
    ownerId: 'demo_business_user', // Fixed ID for demo login matching
    isPromoted: true,
    hasDelivery: true,
    isPublicService: false,
    offer: {
      title: 'Serpme Kahvaltıda %20 İndirim',
      description: 'Hafta içi 11:00\'e kadar geçerli.',
      validUntil: '2024-12-31',
      discountRate: '%20'
    },
    products: [
      { id: 'p1', name: 'Serpme Kahvaltı (2 Kişilik)', price: 450, description: 'Peynir tabağı, reçeller, bal kaymak, sahanda yumurta...' },
      { id: 'p2', name: 'Kayseri Mantısı', price: 180, description: 'Yoğurtlu ve soslu.' },
      { id: 'p3', name: 'Gözleme Çeşitleri', price: 90, description: 'Peynirli, Patatesli veya Ispanaklı' }
    ]
  },
  {
    id: '2',
    name: 'Elit Organizasyon',
    category: Category.EVENTS,
    description: 'Düğün, nişan ve özel günleriniz için profesyonel çözümler.',
    address: 'İstasyon Meydanı No:5',
    phone: '905552223344',
    imageUrl: 'https://picsum.photos/400/300?random=2',
    rating: 4.9,
    tags: ['düğün', 'nişan', 'kına', 'süsleme'],
    status: 'approved',
    isPromoted: true,
    hasDelivery: false,
    isPublicService: false,
    products: [
      { id: 'p1', name: 'Nişan Masası Süsleme', price: 3500, description: 'Arka fon, maket pasta, jardinyer seti.' },
      { id: 'p2', name: 'Gelin Yolu Süsleme', price: 2000, description: '8 adet sütun ve çiçekler.' }
    ]
  },
  {
    id: '3',
    name: 'Pırlanta Güzellik Merkezi',
    category: Category.BEAUTY,
    description: 'Cilt bakımı, lazer ve saç tasarımı.',
    address: 'Lale Sok. No:3',
    phone: '905553334455',
    imageUrl: 'https://picsum.photos/400/300?random=3',
    rating: 4.5,
    tags: ['kuaför', 'makyaj', 'gelin başı'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    offer: {
      title: 'Gelin Paketi Kampanyası',
      description: 'Saç + Makyaj + Cilt Bakımı sadece 2500 TL.',
      validUntil: '2024-08-30'
    },
    products: [
      { id: 'p1', name: 'Gelin Başı & Makyaj', price: 2500, description: 'Prova dahildir.' },
      { id: 'p2', name: 'Klasik Cilt Bakımı', price: 800, description: '60 dakika derinlemesine temizlik.' },
      { id: 'p3', name: 'Manikür & Pedikür', price: 400, description: 'Kalıcı oje seçeneği ile.' }
    ]
  },
  {
    id: '4',
    name: 'Merkez Çiçekçilik',
    category: Category.SHOPPING,
    description: 'Taze kesme çiçekler ve aranjmanlar.',
    address: 'Çarşı İçi No:22',
    phone: '905554445566',
    imageUrl: 'https://picsum.photos/400/300?random=4',
    rating: 4.2,
    tags: ['çiçek', 'gelin çiçeği', 'aranjman'],
    status: 'approved',
    hasDelivery: true,
    isPublicService: false,
    products: [
      { id: 'p1', name: 'Gül Buketi (10\'lu)', price: 600, description: 'İthal kırmızı güller.' },
      { id: 'p2', name: 'Orkide (Çift Dallı)', price: 850, description: 'Seramik saksıda.' }
    ]
  },
  {
    id: '5',
    name: 'Usta Oto Tamir',
    category: Category.AUTOMOTIVE,
    description: 'Her marka araç için güvenilir servis.',
    address: 'Sanayi Sitesi C Blok',
    phone: '905556667788',
    imageUrl: 'https://picsum.photos/400/300?random=5',
    rating: 4.7,
    tags: ['tamir', 'bakım', 'yağ değişimi'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: [
      { id: 'p1', name: 'Periyodik Bakım', price: 1500, description: 'Yağ ve filtre değişimi (Parça hariç işçilik).' },
      { id: 'p2', name: 'Kışlık Bakım Kontrolü', price: 500, description: 'Antifriz ve lastik kontrolü.' }
    ]
  },
  {
    id: '6',
    name: 'Fotoğrafçı Ahmet',
    category: Category.SERVICES,
    description: 'Düğün hikayesi ve dış çekim uzmanı.',
    address: 'Kültür Cad. No:8',
    phone: '905557778899',
    imageUrl: 'https://picsum.photos/400/300?random=6',
    rating: 4.9,
    tags: ['fotoğraf', 'düğün', 'video'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: [
      { id: 'p1', name: 'Dış Çekim Albüm Paketi', price: 5000, description: 'Panoramik albüm + 2 aile albümü + poster.' },
      { id: 'p2', name: 'Düğün Hikayesi Klibi', price: 4000, description: 'Tüm gün video çekimi ve kurgu.' }
    ]
  },
  {
    id: '7',
    name: 'Burger Station',
    category: Category.FOOD,
    description: 'El yapımı hamburgerler ve özel soslar.',
    address: 'Gençlik Cad. No:15',
    phone: '905558889900',
    imageUrl: 'https://picsum.photos/400/300?random=7',
    rating: 4.6,
    tags: ['burger', 'fast food', 'öğrenci dostu'],
    status: 'approved',
    hasDelivery: true,
    isPublicService: false,
    offer: {
      title: '2. Burger Bedava',
      description: 'Her Salı günü geçerli.',
      validUntil: '2024-12-31',
      discountRate: '1 al 1 bedava'
    },
    products: [
      { id: 'p1', name: 'Cheeseburger Menü', price: 220, description: '140gr köfte, patates ve içecek.' },
      { id: 'p2', name: 'Tavuk Burger Menü', price: 180, description: 'Çıtır tavuk, patates ve içecek.' },
      { id: 'p3', name: 'Soğan Halkası (8\'li)', price: 60, description: 'Özel sos ile.' }
    ]
  },
  {
    id: '8',
    name: 'Merkez Eczanesi (Nöbetçi)',
    category: Category.HEALTH,
    description: 'Sağlık danışmanlığı ve dermo-kozmetik ürünler.',
    address: 'Hastane Karşısı',
    phone: '905559990011',
    imageUrl: 'https://picsum.photos/400/300?random=8',
    rating: 5.0,
    tags: ['eczane', 'sağlık', 'kozmetik'],
    status: 'approved',
    hasDelivery: true,
    isPublicService: false,
    products: [
      { id: 'p1', name: 'Güneş Kremi 50+', price: 450, description: 'Hassas ciltler için.' },
      { id: 'p2', name: 'Vitamin C Serumu', price: 350, description: 'Aydınlatıcı etki.' }
    ]
  },
  {
    id: '9',
    name: 'İlçe Halk Kütüphanesi',
    category: Category.PUBLIC,
    description: 'Hafta içi 08:30 - 17:30 arası hizmet vermektedir. Ücretsiz internet ve çalışma salonu mevcuttur.',
    address: 'Merkez Mah. Okul Sok. No:4',
    phone: '02121111111',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&q=80',
    rating: 4.8,
    tags: ['kütüphane', 'kitap', 'ders çalışma'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: true,
    products: []
  },
  // --- YENİ EKLENEN İŞLETMELER ---
  {
    id: '11',
    name: 'Best Restaurant (Balık & Meze)',
    category: Category.FOOD,
    description: 'Çevlik yolu üzerinde, taze mevsim balıkları ve zengin meze çeşitleri ile aile ortamı.',
    address: 'Kapısuyu Mah. (Çevlik Yolu Üzeri)',
    phone: '903265949224',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80',
    rating: 4.7,
    tags: ['balık', 'meze', 'alkollü', 'manzara'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: [
      { id: 'p1', name: 'Levrek Izgara', price: 450, description: 'Mevsim salata ile servis edilir.' },
      { id: 'p2', name: 'Karides Güveç', price: 380, description: 'Tereyağlı ve sarımsaklı.' },
      { id: 'p3', name: 'Humus & Meze Tabağı', price: 250, description: 'Yöresel meze çeşitleri.' }
    ]
  },
  {
    id: '12',
    name: 'Çökmez Restaurant',
    category: Category.FOOD,
    description: 'Samandağ merkezde, yöresel lezzetlerin buluşma noktası.',
    address: 'Samandağ Merkez/Çevlik Yolu',
    phone: '903265949224',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80',
    rating: 4.5,
    tags: ['kebap', 'aile', 'yerel'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '13',
    name: 'Meydan Restoran',
    category: Category.FOOD,
    description: 'Deniz mahallesinde, sahil kenarında ferah bir ortam.',
    address: 'Deniz Mahallesi (Sahil)',
    phone: '903265120033',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80',
    rating: 4.4,
    tags: ['sahil', 'akşam yemeği', 'manzara'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '14',
    name: 'Truva Life Restaurant',
    category: Category.FOOD,
    description: 'Deniz ve güneşin tadını çıkarırken eşsiz lezzetler.',
    address: 'Deniz Sitesi, Kumsal Sokak',
    phone: '905376488787',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80',
    rating: 4.6,
    tags: ['deniz', 'eğlence', 'yemek'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '15',
    name: '1990 Fırat Restaurant',
    category: Category.FOOD,
    description: 'Mehmet Aslan caddesinde yılların değişmeyen lezzeti.',
    address: 'Mehmet Aslan Cad.',
    phone: '903265124142',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80',
    rating: 4.3,
    tags: ['sulu yemek', 'esnaf lokantası'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '16',
    name: 'Talibin Yeri (Kasap & Ocakbaşı)',
    category: Category.FOOD,
    description: 'Taze etlerinizi kasap reyonundan seçin, ocakbaşında pişirelim.',
    address: 'Atatürk Cad. No:142',
    phone: '905378909821',
    imageUrl: 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?auto=format&fit=crop&q=80',
    rating: 4.8,
    tags: ['ocakbaşı', 'kasap', 'mangal'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '17',
    name: 'Saray Döner',
    category: Category.FOOD,
    description: 'Özel soslu Hatay döneri ve dürüm çeşitleri.',
    address: 'Tekebaşı Mah. Sahil Cad. No:225',
    phone: '905388144030',
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80',
    rating: 4.5,
    tags: ['döner', 'dürüm', 'paket servis'],
    status: 'approved',
    hasDelivery: true,
    isPublicService: false,
    products: [
      { id: 'p1', name: 'Tavuk Döner Dürüm', price: 120, description: 'Özel soslu' },
      { id: 'p2', name: 'Et Döner Dürüm', price: 180, description: 'Yaprak döner' }
    ]
  },
  {
    id: '18',
    name: 'Dervişan Tesisleri',
    category: Category.FOOD,
    description: 'Geniş bahçesi ve doğal ortamıyla kahvaltı ve yemek keyfi.',
    address: 'Uğur Mumcu Cad.',
    phone: '903265121656',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80',
    rating: 4.4,
    tags: ['kahvaltı', 'tesis', 'bahçe'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '19',
    name: 'Truva Life Otel',
    category: Category.SERVICES,
    description: 'Deniz kenarında konforlu konaklama ve tatil imkanı.',
    address: 'Deniz Mah. Kumsal Sok. No:29',
    phone: '905376488787',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80',
    rating: 4.5,
    tags: ['otel', 'konaklama', 'tatil'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '20',
    name: 'Riva Otel',
    category: Category.SERVICES,
    description: 'Merkezi konumda, temiz ve nezih odalar.',
    address: 'Deniz Mah. No:198',
    phone: '905353746882',
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80',
    rating: 4.2,
    tags: ['otel', 'konaklama', 'pansiyon'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '21',
    name: 'Luna Bungalov',
    category: Category.SERVICES,
    description: 'Doğa ile iç içe, huzurlu bir bungalov deneyimi.',
    address: 'Hıdırbey Mah. Kapısuyu Yolu',
    phone: '905325725088',
    imageUrl: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?auto=format&fit=crop&q=80',
    rating: 4.9,
    tags: ['bungalov', 'doğa', 'kamp'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '22',
    name: 'Akdeniz Motel & Pansiyon',
    category: Category.SERVICES,
    description: 'Kapısuyu mahallesinde ekonomik ve rahat konaklama.',
    address: 'Kapısuyu Mah. Vali İsmet Gürbüz Cad.',
    phone: '905364343661',
    imageUrl: 'https://images.unsplash.com/photo-1560067174-c5a3a8f37060?auto=format&fit=crop&q=80',
    rating: 4.0,
    tags: ['motel', 'pansiyon', 'ucuz konaklama'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '23',
    name: 'Samandağ Devlet Hastanesi',
    category: Category.PUBLIC,
    description: 'Bölge halkına 7/24 sağlık hizmeti sunan tam teşekküllü devlet hastanesi.',
    address: 'Atatürk Mah. Ortaokul Cad.',
    phone: '903265123880',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80',
    rating: 4.5,
    tags: ['hastane', 'sağlık', 'acil', 'doktor'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: true,
    products: []
  },
  {
    id: '24',
    name: 'Sumaytaoğlu Eczanesi',
    category: Category.HEALTH,
    description: 'İlaç, medikal ürünler ve sağlık danışmanlığı.',
    address: 'Hastane Caddesi No:12',
    phone: '903265120278',
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&q=80',
    rating: 5.0,
    tags: ['eczane', 'ilaç', 'medikal'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '25',
    name: 'Orhan Eczanesi',
    category: Category.HEALTH,
    description: 'Reçeteli ve reçetesiz ilaç temini.',
    address: 'Ortaokul Caddesi No:10',
    phone: '903265120063',
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80',
    rating: 4.8,
    tags: ['eczane', 'ilaç'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '26',
    name: 'Burç Eczanesi',
    category: Category.HEALTH,
    description: 'Çiğdede mahallesinde hizmetinizde.',
    address: 'Çiğdede Mah. Mehmet Aslan Cad.',
    phone: '903265127006',
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80',
    rating: 4.7,
    tags: ['eczane', 'sağlık'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '27',
    name: 'Ege Eczanesi',
    category: Category.HEALTH,
    description: 'Dr. Mithat Abacı caddesi üzerinde.',
    address: 'Dr. Mithat Abacı Cad.',
    phone: '903265126467',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80',
    rating: 4.8,
    tags: ['eczane', 'sağlık'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  },
  {
    id: '28',
    name: 'Şifa Eczanesi (Tomruksuyu)',
    category: Category.HEALTH,
    description: 'Tomruksuyu mahallesinde sağlık hizmeti.',
    address: 'Tomruksuyu Mah. Uğur Mumcu Cad.',
    phone: '903265849074',
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&q=80',
    rating: 4.9,
    tags: ['eczane', 'ilaç', 'tomruksuyu'],
    status: 'approved',
    hasDelivery: false,
    isPublicService: false,
    products: []
  }
];